ceph/urls.py
from django.conf.urls import include, url
from django.contrib import admin
import demo
from demo import views as demo_views

urlpatterns = [
    url(r'^$', demo_views.home, name='home'),
    url(r'^demo/', include('demo.urls')),
    url(r'^admin/', admin.site.urls),
]

demo/urls.py
from django.conf.urls import url
from . import views

app_name = 'demo'
urlpatterns = [
    # /
    url(r'^$', views.index, name='index'),
    # /accounts/login
    url(r'^accounts/login/$', views.login, name='login'),
    # /accounts/logout
    url(r'^accounts/logout/$', views.logout, name='logout'),
    # /accounts/request_login
    url(r'^accounts/request_login/$', views.request_login, 
                                      name='request_login'),
    # /object/myobject
    url(r'^object/(?P<object_name>[a-zA-Z0-9\-]+)/$', 
        views.details, name='details'),
    # /object/myobject/edit
    url(r'^object/(?P<object_name>[a-zA-Z0-9\-]+)/edit/$', 
        views.edit, name='edit'),
    # /object/myobject/update
    url(r'^object/(?P<object_name>[a-zA-Z0-9\-]+)/update/$', 
        views.update, name='update'),
    # /object/myobject/delete
    url(r'^object/(?P<object_name>[a-zA-Z0-9\-]+)/delete/$', 
        views.delete, name='delete'),
    # /create
    url(r'^create/$', views.create, name='create'),
    # /store
    url(r'^store/$', views.store, name='store'),
]

demo/models.py
from django.db import models

# Create your models here.

demo/forms.py
from django import forms
from django.forms import Form, CharField, BooleanField, Textarea
from django.forms import TextInput, PasswordInput, CheckboxInput
from django.forms import HiddenInput

class EditObjectForm(Form):
    # Object name
    attrs = {'readonly': 'readonly'}
    object_name = CharField(widget=TextInput(attrs=attrs))

    # Data
    attrs = {'autofocus': 'autofocus', 'required': 'true'}
    data = CharField(widget=Textarea(attrs=attrs))

class CreateObjectForm(Form):
    # Object name
    attrs = {'autofocus': 'autofocus', 'required': 'true'}
    object_name = CharField(widget=TextInput(attrs=attrs))

    # Data
    attrs = {'required': 'true'}
    data = CharField(widget=Textarea(attrs=attrs))

class LoginForm(Form):
    # User name
    attrs = {'autofocus': 'autofocus', 'required': 'true'}
    username = CharField(widget=TextInput(attrs=attrs))

    attrs = {'required': 'true'}
    password = CharField(widget=PasswordInput(attrs=attrs))

    remember_me = BooleanField(required=False, initial=True)
    
    next_url = CharField(widget=HiddenInput())

demo/views.py
from django.contrib import messages
from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.contrib.auth import logout as auth_logout
from django.contrib.auth.decorators import login_required
from django.core.urlresolvers import reverse
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.views import generic

from . import ssh_utils as utils
from .forms import CreateObjectForm, EditObjectForm, LoginForm


def home(request):
    return HttpResponseRedirect(reverse('demo:index'))

def login(request):
    initial = {
        'remember_me': 'true',
        'next_url': request.GET.get('next', reverse('demo:index'))
    }
    context = {
        'title': 'Log In',
        'form': LoginForm(initial=initial),
    }
    return render(request, 'demo/login.html', context)

def request_login(request):
    if request.method != 'POST':
        messages.add_message(request, messages.INFO,
                             'Invalid request.')
        return HttpResponseRedirect(reverse('demo:login'))

    form = LoginForm(request.POST)
    if not form.is_valid():
        messages.add_message(request, messages.INFO,
                             'Invalid credentials.')
        return HttpResponseRedirect(reverse('demo:login'))
        
    username = form.cleaned_data['username']
    password = form.cleaned_data['password']
    next_url = form.cleaned_data['next_url']
    user = authenticate(username=username, password=password)
    if user is None:
        messages.add_message(request, messages.INFO,
                             'Incorrect username of password.')
        return HttpResponseRedirect(reverse('demo:login'))

    if not user.is_active:
        messages.add_message(request, messages.INFO,
                             'Sorry, this account has been disabled.')
        return HttpResponseRedirect(reverse('demo:login'))

    auth_login(request, user)
    return HttpResponseRedirect(next_url)

def logout(request):
    auth_logout(request)
    return HttpResponseRedirect(reverse('demo:login'))

@login_required
def index(request):
    context = {
        'data': sorted(utils.get_object_list()),
        'title': 'Dashboard',
    }
    return render(request, 'demo/index.html', context)

@login_required
def details(request, object_name):
    data = utils.get_data(object_name)
    context = {
        'title': object_name,
        'object_name': object_name,
        'data': data,
    }
    return render(request, 'demo/details.html', context)

@login_required
def edit(request, object_name):
    data = utils.get_data(object_name)
    form = EditObjectForm(initial={'data': data, 
                                   'object_name': object_name})
    context = {
        'title': 'Edit ' + object_name,
        'object_name': object_name,
        'data': data,
        'form': form,
    }
    return render(request, 'demo/edit.html', context)

@login_required
def update(request, object_name):
    if request.method != 'POST':
        return HttpResponseRedirect(reverse('demo:index'))

    if not utils.is_valid_name(object_name):
        messages.add_message(request, messages.INFO,
            'Invalid object name. Only letters, numbers ' + \
            'and dashes are allowed.')
        return HttpResponseRedirect(reverse('demo:index'))

    form = EditObjectForm(request.POST)
    if not form.is_valid():
        messages.add_message(request, messages.INFO,
                             'The data provided was invalid.')
        return HttpResponseRedirect(reverse('demo:edit', 
                                            args=(object_name,)))
        
    data = form.cleaned_data['data']
    if utils.store_object(object_name, data):
        message = 'Object stored successfully.'
    else:
        message = 'Unable to complete the request.'
    messages.add_message(request, messages.INFO, message)
    return HttpResponseRedirect(reverse('demo:details',
                                        args=(object_name,)))

@login_required
def delete(request, object_name):
    if request.method != 'POST':
        return HttpResponseRedirect(reverse('demo:index'))

    if not utils.exists(object_name):
        messages.add_message(request, messages.INFO,
            'Object %s not found.' % object_name)
        return HttpResponseRedirect(reverse('demo:index'))
    else:
        utils.delete_object(object_name)
        messages.add_message(request, messages.INFO,
            'Object %s deleted!' % object_name)
        return HttpResponseRedirect(reverse('demo:index'))
        
@login_required
def create(request):
    form = CreateObjectForm()
    context = {
        'title': 'Create New Object',
        'form': form,
    }
    return render(request, 'demo/create.html', context)

@login_required
def store(request):
    if request.method != 'POST':
        return HttpResponseRedirect(reverse('demo:index'))

    form = CreateObjectForm(request.POST)
    if not form.is_valid():
        messages.add_message(request, messages.INFO,
                             'The data provided was invalid.')
        return HttpResponseRedirect(reverse('demo:create'))
        
    data = form.cleaned_data['data']
    object_name = form.cleaned_data['object_name']
    if not utils.is_valid_name(object_name):
        messages.add_message(request, messages.INFO,
            'Invalid object name. Only letters, numbers ' + \
            'and dashes are allowed.')
        return HttpResponseRedirect(reverse('demo:create'))

    if utils.exists(object_name):
        messages.add_message(request, messages.INFO,
            'Object already exists!')
        return HttpResponseRedirect(reverse('demo:create'))

    if utils.store_object(object_name, data):
        message = 'Object created successfully.'
    else:
        message = 'Unable to complete the request.'
                             
    messages.add_message(request, messages.INFO, message)
    return HttpResponseRedirect(reverse('demo:details',
                                        args=(object_name,)))

demo/templates/demo/base.html
<!DOCTYPE html>
<html lang="en">
  <head>
    {% include 'demo/metadata.html' %}
    <title>Ceph Demo - {{ title }}</title>
    {% include 'demo/static_files.html' %}
  </head>
  <body>
    {% include 'demo/navbar.html' %}
    <div class="container-fluid">
      <div class="row">
        {% include 'demo/sidebar.html' %}
        <div class="col-sm-9 col-sm-offset-3 col-md-10 col-md-offset-2 main">
          {% block content %}
          {% endblock %}
        </div>
      </div>
    </div>
    {% include 'demo/footer_js.html' %}
  </body>
</html>

demo/templates/demo/create.html
{% extends 'demo/base.html' %}
{% load crispy_forms_tags %}

{% block content %}
<h1 class="page-header">Create New Object</h1>
{% include 'demo/messages.html' %}
<div class="row">
  <div class="col-sm-8">
    <form action="{% url 'demo:store' %}" method="post">
      {% csrf_token %}
      <p>{{ form|crispy }}</p>
      <p>
        <input class="btn btn-lg btn-primary" 
               type="submit" value="Save"/>
        <a class="btn btn-lg btn-primary" 
           href="{% url 'demo:index' %}" 
           role="button">Back</a></p>
      </p>
    </form>
  </div>
</div>
{% endblock %}

demo/templates/demo/details.html
{% extends 'demo/base.html' %}

{% block content %}

<h1 class="page-header">Contents of {{ object_name }}</h1>
{% include 'demo/messages.html' %}

<form name="delete_button" method="post" 
      action="{% url 'demo:delete' object_name %}">
  {% csrf_token %}
  {% if data %}
    <div class="jumbotron">
      <p class="lead" id="detailsbox">{{ data }}</p>
    </div>
    <a class="btn btn-lg btn-primary" 
       href="{% url 'demo:edit' object_name %}" role="button">Edit</a>
    <a class="btn btn-lg btn-primary" 
       href="{% url 'demo:index' %}" role="button">Back</a>
    <input type="hidden" name="supporttype" />
    <input type="submit" value="Delete" class="btn btn-lg btn-danger"/>
  {% else %}
    <h4>Object <strong>{{ object_name }}</strong> not found.</h4><br>
  {% endif %}
</form>

{% endblock %}

demo/templates/demo/edit.html
{% extends 'demo/base.html' %}
{% load crispy_forms_tags %}

{% block content %}

<h1 class="page-header">Edit {{ object_name }}</h1>
{% include 'demo/messages.html' %}

<div class="row">
  <div class="col-sm-8">
    {% if data %}
      <form action="{% url 'demo:update' object_name %}" method="post">
        {% csrf_token %}
        {{ form|crispy }}
        <input class="btn btn-lg btn-primary" 
               type="submit" value="Save" />
        <a class="btn btn-lg btn-primary" 
           href="{% url 'demo:details' object_name %}" 
           role="button">Cancel</a>
      </form>
    {% else %}
      <h4>Object <strong>{{ object_name }}</strong> not found.</h4>
      <a class="btn btn-lg btn-success" 
         href="{% url 'demo:index' %}" role="button">Back</a>
    {% endif %}
  </div>
</div>
{% endblock %}

demo/templates/demo/footer_js.html
{% load staticfiles %}

<!-- Bootstrap core JavaScript
================================================== -->
<!-- Placed at the end of the document so the pages load faster -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script>
<script>window.jQuery || document.write('<script src="{% static 'demo/js/jquery.min.js' %}"><\/script>')</script>
<script src="{% static 'demo/js/bootstrap.min.js' %}"></script>
<!-- Just to make our placeholder images work. Don't actually copy the next line! -->
<script src="{% static 'demo/js/holder.min.js' %}"></script>
<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<script src="{% static 'demo/js/ie10-viewport-bug-workaround.js' %}"></script>

demo/templates/demo/graphs.html
<div class="row placeholders">
  <div class="col-xs-6 col-sm-3 placeholder">
    <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
    <h4>Label</h4>
    <span class="text-muted">Something else</span>
  </div>
  <div class="col-xs-6 col-sm-3 placeholder">
    <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
    <h4>Label</h4>
    <span class="text-muted">Something else</span>
  </div>
  <div class="col-xs-6 col-sm-3 placeholder">
    <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
    <h4>Label</h4>
    <span class="text-muted">Something else</span>
  </div>
  <div class="col-xs-6 col-sm-3 placeholder">
    <img src="data:image/gif;base64,R0lGODlhAQABAIAAAHd3dwAAACH5BAAAAAAALAAAAAABAAEAAAICRAEAOw==" width="200" height="200" class="img-responsive" alt="Generic placeholder thumbnail">
    <h4>Label</h4>
    <span class="text-muted">Something else</span>
  </div>
</div>

demo/templates/demo/index.html
{% extends 'demo/base.html' %}

{% block content %}
{% include 'demo/messages.html' %}
<h1 class="page-header">Dashboard</h1>
{% include 'demo/graphs.html' %}
<h2 class="sub-header">
{% if data %}
  {{ data|length }} Objects Available
{% else %}
  No Objects Available
{% endif %}
 - <a href="{% url 'demo:create' %}">Create New</a>
</h2>
<div class="table-responsive">
  <table class="table table-striped">
    <thead>
      <tr>
        <th>#</th>
        <th>Object Name</th>
        <th></th>
      </tr>
    </thead>
    <tbody>
      {% for object_name in data %}
      <tr>
        <td>{{ forloop.counter }}</td>
        <td><a href="{% url 'demo:details' object_name %}">
            {{ object_name }}</a></td>
        <td><a href="{% url 'demo:edit' object_name %}">edit</a></td>
      </tr>
      {% endfor %}
    </tbody>
  </table>
</div>
{% endblock %}

demo/templates/demo/login.html
{% load staticfiles %}
{% load crispy_forms_tags %}

<!DOCTYPE html>
<html lang="en">
  <head>
    {% include 'demo/metadata.html' %}
    <title>Ceph Demo - {{ title }}</title>
    {% include 'demo/static_files.html' %}
    <!-- Custom bootstrap styles for the login page -->
    <link href="{% static 'demo/css/signin.css' %}" rel="stylesheet">
    <!-- My custom styles for the login page -->
    <link href="{% static 'demo/css/my-signin.css' %}" rel="stylesheet">
  </head>
  <body>
    <div class="container">
      <form class="form-signin" action="{% url 'demo:request_login' %}"
            method="post">
        <h2 class="form-signin-heading">Please sign in</h2>
        {% include 'demo/messages.html' %}
        {% csrf_token %}
        {{ form|crispy }}
        <button class="btn btn-lg btn-primary btn-block" 
                type="submit">Sign in</button>
      </form>
    </div> <!-- /container -->
  </body>
</html>

demo/templates/demo/messages.html
{% if messages %}
  {% for message in messages %}
    <div class="alert alert-info">{{ message }}</div>
  {% endfor %}
{% endif %}

demo/templates/demo/metadata.html
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
<meta name="description" content="">
<meta name="author" content="">
<link rel="icon" href="demo/favicon.ico">

demo/templates/demo/navbar.html
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container-fluid">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" href="{% url 'demo:index' %}">Ceph Demo</a>
    </div>
    <div id="navbar" class="navbar-collapse collapse">
      <ul class="nav navbar-nav navbar-right">
        <li><a href="#">Help</a></li>
        <li><a href="#">Settings</a></li>
        <li><a href="#">Profile</a></li>
        <li><a href="{% url 'demo:logout' %}">Log out</a></li>
      </ul>
      <form class="navbar-form navbar-right">
        <input type="text" class="form-control" placeholder="Search...">
      </form>
    </div>
  </div>
</nav>

demo/templates/demo/sidebar.html
<div class="col-sm-3 col-md-2 sidebar">
  <ul class="nav nav-sidebar">
    <li class="active"><a href="#">Overview <span class="sr-only">(current)</span></a></li>
    <li><a href="#">Reports</a></li>
    <li><a href="#">Analytics</a></li>
    <li><a href="#">Export</a></li>
  </ul>
  <ul class="nav nav-sidebar">
    <li><a href="">Nav item</a></li>
    <li><a href="">Nav item again</a></li>
    <li><a href="">One more nav</a></li>
    <li><a href="">Another nav item</a></li>
    <li><a href="">More navigation</a></li>
  </ul>
  <ul class="nav nav-sidebar">
    <li><a href="">Nav item again</a></li>
    <li><a href="">One more nav</a></li>
    <li><a href="">Another nav item</a></li>
  </ul>
</div>

demo/templates/demo/static_files.html
{% load staticfiles %}

<!-- Bootstrap core CSS -->
<link href="{% static 'demo/css/bootstrap.min.css' %}" rel="stylesheet">

<!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
<link href="{% static 'demo/css/ie10-viewport-bug-workaround.css' %}" rel="stylesheet">

<!-- Custom styles for the dashboard -->
<link href="{% static 'demo/css/dashboard.css' %}" rel="stylesheet">

<!-- Display new lines in the details view -->
<link href="{% static 'demo/css/details.css' %}" rel="stylesheet">

<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
<!--[if lt IE 9]>
  <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
  <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->